import "@shawnsandy/first-paint/dist/css/libs/all.min.css";
import "./globals.css";
import { Inter } from "next/font/google";
import PageHeader from "@/components/page-header";
import { Text } from "@fpkit/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
