import "@shawnsandy/first-paint/dist/css/libs/all.min.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@fpkit/nextra";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header styles={{ marginTop: "3rem" }}>
          <section>
            <h2>Header Section</h2>
            <p>
              Labore est esse et nulla anim labore consequat veniam cupidatat
              laborum adipisicing.
            </p>
            <p>
              <button type="button">Default Button</button>
            </p>
          </section>
        </Header>
        {children}
      </body>
    </html>
  );
}
